// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_mUpkH_OpOPpfyqYcGH24wuo5W6Cii54',
    appId: '1:1099274989417:android:d5dcc4b13e6d88c4f8d7f8',
    messagingSenderId: '1099274989417',
    projectId: 'stress-relief-app-f5c1f',
    storageBucket: 'stress-relief-app-f5c1f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSzPFC7YOyLhBDoOcaVlYZek1IeBxyKc',
    appId: '1:1099274989417:web:02bb7793717517c6f8d7f8',
    messagingSenderId: '1099274989417',
    projectId: 'stress-relief-app-f5c1f',
    storageBucket: 'stress-relief-app-f5c1f.firebasestorage.app',
    authDomain: 'stress-relief-app-f5c1f.firebaseapp.com',
    databaseURL: 'https://stress-relief-app-f5c1f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
