import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'app_theme.dart';
import '../providers/theme_provider.dart';

/// Extension để dùng context.theme thay vì AppColors
extension BuildContextTheme on BuildContext {
  /// Access custom AppTheme (for backward compatibility)
  AppTheme get theme {
    try {
      return watch<ThemeProvider>().currentTheme;
    } catch (e) {
      // Fallback nếu chưa có Provider
      return AppThemes.pastelBlueBreeze;
    }
  }

  // ==================== M3 SEMANTIC COLORS ====================

  /// Access Material 3 ColorScheme
  ColorScheme get colorScheme => Theme.of(this).colorScheme;

  /// Primary colors
  Color get primaryColor => colorScheme.primary;
  Color get onPrimary => colorScheme.onPrimary;
  Color get primaryContainer => colorScheme.primaryContainer;
  Color get onPrimaryContainer => colorScheme.onPrimaryContainer;

  /// Secondary colors
  Color get secondaryColor => colorScheme.secondary;
  Color get onSecondary => colorScheme.onSecondary;
  Color get secondaryContainer => colorScheme.secondaryContainer;
  Color get onSecondaryContainer => colorScheme.onSecondaryContainer;

  /// Tertiary colors (generated by M3)
  Color get tertiaryColor => colorScheme.tertiary;
  Color get onTertiary => colorScheme.onTertiary;
  Color get tertiaryContainer => colorScheme.tertiaryContainer;
  Color get onTertiaryContainer => colorScheme.onTertiaryContainer;

  /// Error colors
  Color get errorColor => colorScheme.error;
  Color get onError => colorScheme.onError;
  Color get errorContainer => colorScheme.errorContainer;
  Color get onErrorContainer => colorScheme.onErrorContainer;

  /// Surface colors
  Color get surfaceColor => colorScheme.surface;
  Color get onSurface => colorScheme.onSurface;
  Color get surfaceVariant => colorScheme.surfaceVariant;
  Color get onSurfaceVariant => colorScheme.onSurfaceVariant;
  Color get surfaceTint => colorScheme.surfaceTint;

  /// Other semantic colors
  Color get outline => colorScheme.outline;
  Color get outlineVariant => colorScheme.outlineVariant;
  Color get shadow => colorScheme.shadow;
  Color get scrim => colorScheme.scrim;
  Color get inverseSurface => colorScheme.inverseSurface;
  Color get onInverseSurface => colorScheme.onInverseSurface;
  Color get inversePrimary => colorScheme.inversePrimary;
}